Short Notes about NumPy:
- NumPy (Numerical Python) is a powerful library for numerical computations in Python.
- Provides a high-performance multidimensional array object called ndarray.
- Supports a wide variety of mathematical, logical, and statistical operations on arrays.
- Essential for scientific computing and forms the foundation for libraries like pandas, SciPy, and scikit-learn.
- Allows broadcasting, vectorization, and efficient operations on big data sets.
- Commonly imported as: import numpy as np


In [1]:
# this will install numpy. we can also install form requirements.txt file
#!pip install numpy 
import numpy as np

In [2]:
# create 1d arr
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)

# create 2d arr
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

# create 3d arr
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr.reshape(2, 5) #reshape the array to 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
# arange means array range
arr = np.arange(1, 10, 2).reshape(5, 1) #start, stop, step
print(arr)

# zeros means zero array
arr = np.zeros(5)
print(arr)

# arr = np.ones(3, 5)  wrong
arr = np.ones((3, 5)) #correct # create 3 rows and 5 columns with element as 1
print(arr)

# identity matrix
arr = np.eye(5) #create 5x5 identity matrix
print(arr)

[[1]
 [3]
 [5]
 [7]
 [9]]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# attributes of array created by numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)               # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)           # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)   # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [6]:
# Numpy vectorized operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element Wise addition
print("Addition:", arr1 + arr2)

# Element Wise Substraction
print("Substraction:", arr1 - arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)



Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [7]:
#  universal array function
arr = np.array([1, 2, 3, 4, 5])
print("Square:", np.square(arr))
print("Square Root:", np.sqrt(arr))
print("Exponent:", np.exp(arr))
print("Logarithm:", np.log(arr))


Square: [ 1  4  9 16 25]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponent: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [8]:
# array slicing and indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0]) #first element
print(arr[1:3]) #second and third element
print(arr[:3]) #first three elements
print(arr[1:]) #all elements except first
print(arr[-1]) #last element

1
[2 3]
[1 2 3]
[2 3 4 5]
5


In [9]:
# Array slicing on 2d array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0]) #first row
print(arr[1:3]) #second and third row
print(arr[:3]) #first three rows
print(arr[1:]) #all rows except first
print(arr[-1]) #last row


[1 2 3]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[7 8 9]


In [10]:
arr[1:, 1: ]

array([[5, 6],
       [8, 9]])

In [11]:
arr[1:] = 5555;
print(arr)

[[   1    2    3]
 [5555 5555 5555]
 [5555 5555 5555]]


In [12]:
arr[1:, 1:] = 6666;
print(arr)

[[   1    2    3]
 [5555 6666 6666]
 [5555 6666 6666]]


In [13]:
# Statistical normalisation means
# to have a mean of 0 and standard deviatioin of 1
data = np.array([1,2,3,4,5,6,7])
#  calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print(mean, std_dev)

normalisedData = (data - mean) / std_dev #this concept will come later
print(normalisedData)

4.0 2.0
[-1.5 -1.  -0.5  0.   0.5  1.   1.5]


In [ ]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.mean(data)) 
print(np.median(data))
print(np.std(data)) #standard deviation
print(np.var(data)) #variance


5.5
5.5
2.8722813232690143
8.25


In [17]:
# Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data > 5)
print(data[data > 5])
print(data[data % 2 == 0])


[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
